import { useEffect, useState } from "react";
import { DailyAdviceResponse, fetchHomeAdvice } from "./services/api";
import { formatDate } from "./utils/format";

/**
 * "Advice for you" note on the Dashboard.
 *
 * One data-grounded tip per 6-hour block, generated by the backend's
 * deterministic insight engine (no AI). Renders nothing while loading or
 * on failure so it never blocks or clutters the dashboard.
 */
function AdviceCard({ onAskChat }: { onAskChat: (message: string) => void }) {
    const [data, setData] = useState<DailyAdviceResponse | null>(null);
    const [failed, setFailed] = useState(false);

    useEffect(() => {
        let cancelled = false;
        fetchHomeAdvice()
            .then((res) => {
                if (!cancelled) setData(res);
            })
            .catch(() => {
                if (!cancelled) setFailed(true);
            });
        return () => {
            cancelled = true;
        };
    }, []);

    if (failed || !data || (!data.advice && !data.message)) return null;

    const chatPrompt = data.advice
        ? `On my dashboard I saw this advice: "${data.advice.headline}" — ${data.advice.detail}. Explain what might be driving this and what I should do about it.`
        : null;

    return (
        <div className={`advice-box ${data.advice?.tone === "warning" ? "advice-warning" : ""}`}>
            <div className="advice-icon">💡</div>
            <div style={{ flex: 1 }}>
                <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", flexWrap: "wrap" }}>
                    <span className="advice-label">Advice for you</span>
                    {data.business_date && (
                        <span className="badge badge-muted">For {formatDate(data.business_date)}</span>
                    )}
                </div>
                {data.advice ? (
                    <>
                        <div className="advice-headline">{data.advice.headline}</div>
                        <div className="advice-detail">{data.advice.detail}</div>
                        <div className="advice-footer">
                            <span className="advice-next">Next tip at {data.next_update}</span>
                            {chatPrompt && (
                                <button className="chip" onClick={() => onAskChat(chatPrompt)}>
                                    Ask AI about this
                                </button>
                            )}
                        </div>
                    </>
                ) : (
                    <div className="advice-detail">{data.message}</div>
                )}
            </div>
        </div>
    );
}

export default AdviceCard;
